@startuml BBショップ注文管理システムクラス図
skinparam classAttributeIconSize 0
hide circle

class ユーザー {
- ユーザーID
- 氏名
- メールアドレス
- パスワード
- 電話番号
- 住所
- 登録日   
+ ログイン()
+ ログアウト()
+ 商品を検索する()
+ 商品を注文する()
+ 注文状況を確認する()
+ 商品を返品する()
+ レビューを投稿する()
}

class 事業者 {
- 事業者ID
- 会社名
- 担当者名
- メールアドレス
- 電話番号
- 住所


+ 図書を借りる()
+ 図書を予約する()
+ 図書を返却する()
}

class 商品 {
- 商品ID
- 商品名
- 価格
- 在庫数
- 説明
- カテゴリ
+ 商品情報を更新する()
+ 在庫を管理する()
+ 商品を削除する()
}

@enduml