@startuml 大原情報科学大学・図書館システムクラス図
skinparam classAttributeIconSize 0
hide circle

class 学生 {
- 学生番号
- 氏名

+ 図書を借りる()
+ 図書を予約する()
+ 図書を返却する()
}

class 教職員 {
- 職員番号
- 氏名

+ 図書を借りる()
+ 図書を予約する()
+ 図書を返却する()
}

class 事務職員 {
- 会員番号
- 氏名
- 生年月日
- 電話番号
- メールアドレス

+ 図書の貸し出し予約の受付をする()
+ 図書の貸し出しと返却を処理する()
+ 貸し出し履歴と図書の予約を閲覧する()

}

class 会員 {
 -会員番号
 -氏名
 -生年月日
 -電話番号
 -メールアドレス

 +予約する()
 +借りる()
 +返却する()

}

class 貸出 {
 -貸出ID
 -貸出日
 -返却期限
 -返却日

 +貸し出す()
 +返却する()

}

class 予約 {
 -予約ID
 -予約日
 -キャンセル日

 +予約する()
 +キャンセルする()

}

class 図書 {
 -管理番号
 -タイトル
 -著者
 -出版社
 -出版年
 -ISBN
 -貸出状況

 +貸し出す()
 +返却する()
 +予約する()

}

@enduml