@startuml Robodogクラス図
skinparam classAttributeIconSize 0
hide circle

class RoboDog {
-MyName: String
 'datetime? bigint?=UNIXTime
 'UniXTime 1970/01/01 00:00:00 を0として、1行ずつ追加するもの
-myTime: int
-goodMorning: String
-goodAfternoon: String
-goodEvening: String
-firstValue: int
-secondValue: int
'教科書に記載されてない
-result: int
 
+getMyName(): String
+setNewName(): int
+setNewTime(): void
+getMyGreeting(): String
'教科書に記載されてない
+setTwoValues(): void
+setAndGetResult(): int
}

@enduml
