@startuml Robodogユースケース図
left to right direction
actor ユーザー as U1

rectangle RoboDog as WRS {
  usecase "名前を変更する" as UC1
  usecase "時刻に応じて挨拶をする" as UC2
  usecase "足し算をする" as UC3
}
U1 --> UC1
U1 --> UC2
U1 --> UC3
@enduml